import { CalendarDay, MenuItem, LedgerItem, UserProfile, Department, MealCallState } from './types';

export const INITIAL_PROFILES: Record<string, UserProfile> = {
  member: {
    id: 'KB-2490',
    name: 'হাসান মাহমুদ',
    nameEn: 'Hasan Mahmud',
    role: 'member',
    designation: 'সিনিয়র অফিসার, আইটি অপারেশন',
    designationEn: 'Senior Officer, IT Operation',
    department: 'আইটি অপারেশন',
    departmentEn: 'IT Operation',
    gpfNo: 'GPF-২৪৯০',
    mobile: '০১৭১৭-৩৪৫৬৭৮',
    email: 'hasan.ict@kbl.gov.bd',
    roomNo: '৪০১ (৪র্থ তলা), প্রধান কার্যালয়',
    roomNoEn: 'Room 401 (4th Fl), Head Office',
    monthlyMeals: 18,
    upcomingMeals: 1,
    advanceBalance: 2500,
    dueAmount: 0,
    todayMealStatus: 'on',
    mealRate: 65,
  },
  admin: {
    id: 'GPF-৫১২৩৪',
    name: 'মো: সাইফুল ইসলাম',
    nameEn: 'Md. Saiful Islam',
    role: 'admin',
    designation: 'মহাব্যবস্থাপক ও মেস ইনচার্জ',
    designationEn: 'General Manager & Mess In-charge',
    department: 'সাধারণ সেবা বিভাগ',
    departmentEn: 'Common Services Department',
    gpfNo: 'GPF-৫১২৩৪',
    mobile: '01911-554433',
    email: 'saiful.admin@kbl.gov.bd',
    roomNo: '২০১, প্রশাসন ভবন',
    roomNoEn: 'Room 201, Administration Building',
    monthlyMeals: 20,
    upcomingMeals: 1,
    advanceBalance: 3200,
    dueAmount: 0,
    todayMealStatus: 'on',
    mealRate: 65,
  },
  coadmin: {
    id: 'GPF-৩৮৯২০',
    name: 'মোহাম্মদ রহিম উল্লাহ',
    nameEn: 'Mohammad Rahim Ullah',
    role: 'coadmin',
    designation: 'অফিসার ও সহকারী মেস ম্যানেজার',
    designationEn: 'Officer & Assistant Mess Manager',
    department: 'কেন্দ্রীয় হিসাব ও তহবিল ব্যবস্থাপনা বিভাগ',
    departmentEn: 'Central Accounts and Fund Management Department',
    gpfNo: 'GPF-৩৮৯২০',
    mobile: '০১৮১২-৯৮৭৬৫৪',
    email: 'rahim.accounts@kbl.gov.bd',
    roomNo: '৩০৫, হিসাব ভবন',
    roomNoEn: 'Room 305, Accounts Building',
    monthlyMeals: 19,
    upcomingMeals: 1,
    advanceBalance: 1800,
    dueAmount: 0,
    todayMealStatus: 'on',
    mealRate: 65,
  },
};

export const INITIAL_MENU: MenuItem[] = [
  {
    id: '1',
    name: 'রুই মাছ',
    nameEn: 'Rui Fish Curry',
    category: 'ঝোল',
    categoryEn: 'Fish Curry',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLZzYzg259kTYLHtjwgcRZ36rsxzRruGqHBpbXedflJULbcePHVZL2H9lCdQtihFG4h_21wX5sJ6thK_Kp-tcPGjblCKF4aKkz3MAewxvUNVNWov3-Oya4zfxCyVOgO1DpPjCGxBPp3rUvyOrzZFZy9llxjDzdGLxmQysSkpLS05q2b76VWMI2JMeEoT2lESndmjGeaQL7z1MnI-H7qt2MQxFWcGzFKcV081MwrtxH-5Rs89BcPxQ-',
  },
  {
    id: '2',
    name: 'মসুর ডাল',
    nameEn: 'Red Lentil (Dal)',
    category: 'ঘন স্পেশাল',
    categoryEn: 'Special Thick Dal',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrLevV5sTh15e2pASCD_kCpMgLddywNH6xLGK5n8iMy7OG7IrxBIev_8z3hYnnBcJwtOQdI03AIUkni8Y0jsShnPgb7Ytu2LD2dzmxQAYVqG3V-VzSklZk7SjQCFxcahc4u_Um5fjCzBShTf5GwjwgFYa_SLaPdI9WTdVydmEYDCh6aKnTmT8TslGfw2tDDdl3w3diqMRcGz2MYeRbdpWqJ0usyKpOAizdL45g8bamWczFOQb48MZY',
  },
  {
    id: '3',
    name: 'মৌসুমি সবজি',
    nameEn: 'Seasonal Mixed Veg',
    category: 'পাঁচমিশেল',
    categoryEn: 'Mixed Vegetable',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNaQtG85SgSfGYGLn1DqY0YL6bajlYXHGVuVgU_uHf53tgJ-sYvw-f2h4i2hLBXOdTJuMzhJsfshS01yY6pffHOMIOX0tbb117XfUHV5-h6AeV0JQdd2k-JRyPIrn39vSp_prXNuc7lGDtWX-m8nF5Cq11lNGS2KYx4Gxmgjuw-6PbaJ4tZecp4jLOywqL7TqAV9GY8ILkneliodDF3ObI4_GNsvqT34kZ8gsI1BZuP1g3OsSTZO8k',
  },
  {
    id: '4',
    name: 'সাদা ভাত',
    nameEn: 'Steamed White Rice',
    category: 'গরম সুগন্ধি',
    categoryEn: 'Hot Steamed Rice',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdiUOK8h_DDjWmom6BtQwCyYebN3FBoRqefPY1fZvg9Tre5MUnJxBHfax1_VMTQ8AKS16ba8aKN_cHrp-I5tDo9r_F0ekgGdTG5Ib88o0iX6ZwAPxCszXYkmj50wymlDFPssBDspJhmhs6G6zq3nFCmIn7UuR7lU-6mxinAFr3XlEpUBqtzt9iRcFhTD1j1TCG3sYjegT6AK5ny-pavYLBbabFS0xY_z9-0bc1M9d3RzUht4BQZEh-',
  },
];

// Generate realistic initial days for the CURRENT month and year
export const generateCurrentMonthInitialDays = (
  targetDate: Date = new Date()
): CalendarDay[] => {
  const year = targetDate.getFullYear();
  const month = targetDate.getMonth();
  const currentDay = targetDate.getDate();
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const result: CalendarDay[] = [];

  for (let d = 1; d <= daysInMonth; d++) {
    const weekday = new Date(year, month, d).getDay(); // 0=Sun..6=Sat
    const isHoliday = weekday === 5 || weekday === 6; // Fri, Sat

    if (isHoliday) {
      result.push({
        day: d,
        weekday,
        status: 'holiday',
        label: 'ছুটি',
        officerMeal: 0,
        guestMeal: 0,
      });
    } else if (d < currentDay) {
      // Past working days in current month
      const booked = (d % 7 !== 3);
      result.push({
        day: d,
        weekday,
        status: booked ? 'cutoff' : 'unbooked',
        label: booked ? '১ মিল' : 'খালি',
        officerMeal: booked ? 1 : 0,
        guestMeal: 0,
        isPast: true,
      });
    } else if (d === currentDay) {
      // TODAY
      result.push({
        day: d,
        weekday,
        status: 'booked',
        label: '১ মিল',
        officerMeal: 1,
        guestMeal: 0,
      });
    } else if (d === currentDay + 1) {
      // Tomorrow
      result.push({
        day: d,
        weekday,
        status: 'booked',
        label: '১ মিল',
        officerMeal: 1,
        guestMeal: 0,
      });
    } else {
      // Future days
      result.push({
        day: d,
        weekday,
        status: 'available',
        label: 'উপলব্ধ',
        officerMeal: 0,
        guestMeal: 0,
      });
    }
  }

  return result;
};

export const INITIAL_OCTOBER_DAYS: CalendarDay[] = generateCurrentMonthInitialDays();

export const INITIAL_LEDGER: LedgerItem[] = [
  {
    id: 'TXN-901',
    date: '০১/১০/২০২৪',
    description: 'ব্যাংক একাউন্ট হতে মাসিক এডভান্স জমা',
    descriptionEn: 'Monthly advance deposit via Bank Account',
    type: 'deposit',
    amount: 3000,
    balanceAfter: 3000,
    ref: 'PAY-KB882',
  },
  {
    id: 'TXN-902',
    date: '০৮/১০/২০২৪',
    description: 'মিল চার্জ কর্তন (২টি মিল: কর্মকর্তা + অতিথি)',
    descriptionEn: 'Meal charge deduction (2 meals: Officer + Guest)',
    type: 'charge',
    amount: 130,
    balanceAfter: 2870,
    ref: 'MEAL-08OCT',
  },
  {
    id: 'TXN-903',
    date: '১০/১০/২০২৪',
    description: 'মিল চার্জ কর্তন (১টি কর্মকর্তা লাঞ্চ)',
    descriptionEn: 'Meal charge deduction (1 officer lunch)',
    type: 'charge',
    amount: 65,
    balanceAfter: 2805,
    ref: 'MEAL-10OCT',
  },
  {
    id: 'TXN-904',
    date: '১৩/১০/২০২৪',
    description: 'মিল চার্জ কর্তন (১টি কর্মকর্তা লাঞ্চ)',
    descriptionEn: 'Meal charge deduction (1 officer lunch)',
    type: 'charge',
    amount: 65,
    balanceAfter: 2740,
    ref: 'MEAL-13OCT',
  },
  {
    id: 'TXN-905',
    date: '১৫/১০/২০২৪',
    description: 'মিল চার্জ বুকিং হোল্ড (১৫ অক্টোবর)',
    descriptionEn: 'Meal charge booking hold (15 October)',
    type: 'charge',
    amount: 65,
    balanceAfter: 2675,
    ref: 'MEAL-15OCT',
  },
];

export const INITIAL_BAZAAR_EXPENSES: import('./types').BazaarExpense[] = [
  {
    id: 'BZ-1015',
    date: '১৫/১০/২০২৪',
    buyerName: 'মোহাম্মদ রহিম উল্লাহ',
    buyerGpf: 'GPF-৩৮৯২০',
    category: 'fish_meat',
    itemsDescription: 'তাজা রুই মাছ ৮.৫ কেজি @ ৩৫০/- ও দেশি চিংড়ি ১ কেজি @ ৮৫০/-',
    amount: 3825,
    voucherNo: 'VCH-KB-9912',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1014',
    date: '১৫/১০/২০২৪',
    buyerName: 'মোহাম্মদ রহিম উল্লাহ',
    buyerGpf: 'GPF-৩৮৯২০',
    category: 'vegetables',
    itemsDescription: 'মৌসুমি সবজি (পটল, পেঁপে, আলু ১০ কেজি, কাঁচামরিচ, ধনেপাতা)',
    amount: 1150,
    voucherNo: 'VCH-KB-9913',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1013',
    date: '১৪/১০/২০২৪',
    buyerName: 'হাসান মাহমুদ',
    buyerGpf: 'GPF-২৪৯০',
    category: 'rice_grains',
    itemsDescription: 'মিনিকেট চাল ৫০ কেজির ১ বস্তা ও প্রিমিয়াম মসুর ডাল ৫ কেজি',
    amount: 4100,
    voucherNo: 'VCH-KB-9880',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1012',
    date: '১৪/১০/২০২৪',
    buyerName: 'হাসান মাহমুদ',
    buyerGpf: 'GPF-২৪৯০',
    category: 'oil_spices',
    itemsDescription: 'তীর সয়াবিন তেল ৫ লিটার, পেঁয়াজ ৫ কেজি, রসুন ও আদা',
    amount: 1980,
    voucherNo: 'VCH-KB-9881',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1011',
    date: '১৩/১০/২০২৪',
    buyerName: 'মো: সাইফুল ইসলাম',
    buyerGpf: 'GPF-৫১২৩৪',
    category: 'fish_meat',
    itemsDescription: 'ফার্মের ব্রয়লার মুরগি ১২ কেজি @ ২১০/- ও ফার্মের ডিম ৬০টি',
    amount: 3220,
    voucherNo: 'VCH-KB-9840',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1010',
    date: '১০/১০/২০২৪',
    buyerName: 'মোহাম্মদ রহিম উল্লাহ',
    buyerGpf: 'GPF-৩৮৯২০',
    category: 'utility_other',
    itemsDescription: 'রান্নার এলপিজি গ্যাস সিলিন্ডার ১টি ও ডিশওয়াশ সাবান/স্ক্রাবার',
    amount: 1450,
    voucherNo: 'VCH-KB-9799',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1009',
    date: '০৮/১০/২০২৪',
    buyerName: 'মোহাম্মদ রহিম উল্লাহ',
    buyerGpf: 'GPF-৩৮৯২০',
    category: 'fish_meat',
    itemsDescription: 'কাতল মাছ ৯ কেজি @ ৩৪০/- এবং টমেটো ও লেবু',
    amount: 3260,
    voucherNo: 'VCH-KB-9750',
    verifiedBy: 'মেস ইনচার্জ',
  },
  {
    id: 'BZ-1008',
    date: '০৬/১০/২০২৪',
    buyerName: 'হাসান মাহমুদ',
    buyerGpf: 'GPF-২৪৯০',
    category: 'rice_grains',
    itemsDescription: 'পোলাও চাল ২ কেজি, চিনিগুঁড়া ও সোনালি মুরগি বিশেষ ভোজের জন্য',
    amount: 2850,
    voucherNo: 'VCH-KB-9710',
    verifiedBy: 'মেস ইনচার্জ',
  },
];

export const INITIAL_BILLING_RECORDS: import('./types').MemberBillingRecord[] = [
  {
    id: 'BILL-01',
    gpfNo: 'GPF-২৪৯০',
    name: 'হাসান মাহমুদ',
    designation: 'সিনিয়র অফিসার',
    department: 'আইটি অপারেশন',
    mobile: '01711-234567',
    officerMeals: 18,
    guestMeals: 2,
    totalMeals: 20,
    mealCost: 1300,
    messFee: 150,
    totalBill: 1450,
    advancePaid: 2500,
    netDue: -1050, // refundable
    status: 'refund',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল ও ডাল', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস ও সবজি', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'দেশি মুরগির ঝোল', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'তাজা রুই মাছ ও মেহমান লাঞ্চ', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও ডাল', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল ও শাক ভাজি', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস ও ভর্তা', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'রুই মাছ ও অতিথি লাঞ্চ', status: 'consumed' },
      { date: '১৬/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও চাটনি', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছ ও সবজি', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির লাল ঝোল', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'দেশি মুরগি ও ডাল', status: 'consumed' },
      { date: '২৩/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও আলু ভর্তা', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল ও সবজি', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন তরকারি ও সালাদ', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া ও ডাল', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০১/১০/২০২৪', amount: 2000, voucherNo: 'TR-KB-882', method: 'ব্যাংক অ্যাকাউন্ট অটো-ডেবিট', notes: 'মাসিক নির্ধারিত অগ্রিম' },
      { date: '১২/১০/২০২৪', amount: 500, voucherNo: 'CR-KB-9921', method: 'ক্যাশ কাউন্টারে জমা', notes: 'অতিরিক্ত অগ্রিম জমা' },
    ],
  },
  {
    id: 'BILL-02',
    gpfNo: 'GPF-৫১২৩৪',
    name: 'মো: সাইফুল ইসলাম',
    designation: 'মহাব্যবস্থাপক ও ইনচার্জ',
    department: 'সাধারণ সেবা বিভাগ',
    mobile: '01819-345678',
    officerMeals: 20,
    guestMeals: 4,
    totalMeals: 24,
    mealCost: 1560,
    messFee: 150,
    totalBill: 1710,
    advancePaid: 3200,
    netDue: -1490,
    status: 'refund',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল', status: 'consumed' },
      { date: '০২/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'ডিম ভুনা ও ভিজিটর লাঞ্চ', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস ও সবজি', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'মুরগির ঝোল ও মেহমান লাঞ্চ', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'তাজা রুই মাছ', status: 'consumed' },
      { date: '০৯/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও ডাল', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'মাছের ঝোল ও ভিজিটর লাঞ্চ', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'রুই মাছ ও মেহমান লাঞ্চ', status: 'consumed' },
      { date: '১৬/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছের ঝোল', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কষা', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির তরকারি', status: 'consumed' },
      { date: '২৩/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও শাক', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০১/১০/২০২৪', amount: 2500, voucherNo: 'TR-KB-811', method: 'ব্যাংক স্যালারি অটো-ডেবিট', notes: 'বেতন হতে অগ্রিম জমা' },
      { date: '১০/১০/২০২৪', amount: 700, voucherNo: 'CR-KB-9410', method: 'ক্যাশ কাউন্টারে জমা', notes: 'অতিথি মিল বাবদ অতিরিক্ত জমা' },
    ],
  },
  {
    id: 'BILL-03',
    gpfNo: 'GPF-৩৮৯২০',
    name: 'মোহাম্মদ রহিম উল্লাহ',
    designation: 'অফিসার',
    department: 'কেন্দ্রীয় হিসাব ও তহবিল ব্যবস্থাপনা বিভাগ',
    mobile: '01712-456789',
    officerMeals: 19,
    guestMeals: 1,
    totalMeals: 20,
    mealCost: 1300,
    messFee: 150,
    totalBill: 1450,
    advancePaid: 1800,
    netDue: -350,
    status: 'refund',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ ও ডাল', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'তাজা রুই মাছ', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'রুই মাছ ও অতিথি লাঞ্চ', status: 'consumed' },
      { date: '১৬/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছের ঝোল', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'দেশি মুরগি', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '২৩/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা ও ডাল', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন ঝোল', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২৯/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০২/১০/২০২৪', amount: 1500, voucherNo: 'TR-KB-843', method: 'ব্যাংক ট্রান্সফার', notes: 'অক্টোবর অগ্রিম জমা' },
      { date: '১৫/১০/২০২৪', amount: 300, voucherNo: 'CR-KB-9520', method: 'ক্যাশ কাউন্টারে জমা', notes: 'মেহমান মিল বাবদ জমা' },
    ],
  },
  {
    id: 'BILL-04',
    gpfNo: 'GPF-১৬৭৮২',
    name: 'মোছা: নাসরিন সুলতানা',
    designation: 'প্রিন্সিপাল অফিসার',
    department: 'ঋণ ও অগ্রিম বিভাগ',
    mobile: '01911-567890',
    officerMeals: 22,
    guestMeals: 0,
    totalMeals: 22,
    mealCost: 1430,
    messFee: 150,
    totalBill: 1580,
    advancePaid: 1500,
    netDue: 80, // due
    status: 'due',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '০২/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল', status: 'consumed' },
      { date: '০৯/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '১৬/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছ', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '২৩/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২৯/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '৩০/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০১/১০/২০২৪', amount: 1500, voucherNo: 'TR-KB-890', method: 'ব্যাংক একাউন্ট ডেবিট', notes: 'চলতি মাসের নির্ধারিত অগ্রিম' },
    ],
  },
  {
    id: 'BILL-05',
    gpfNo: 'GPF-২৯০১১',
    name: 'কাজী মিজানুর রহমান',
    designation: 'সহকারী মহাব্যবস্থাপক',
    department: 'নিরীক্ষা ও পরিদর্শন বিভাগ',
    mobile: '01678-678901',
    officerMeals: 16,
    guestMeals: 5,
    totalMeals: 21,
    mealCost: 1365,
    messFee: 150,
    totalBill: 1515,
    advancePaid: 1515,
    netDue: 0,
    status: 'cleared',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'মুরগির মাংস ও অতিথি লাঞ্চ', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 2, totalMeals: 3, menuItem: 'মাছের ঝোল ও ২ অতিথি লাঞ্চ', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'রুই মাছ ও মেহমান লাঞ্চ', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছ', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'তাজা মাছ ও মেহমান লাঞ্চ', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন মাংস', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২৯/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '৩০/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '৩১/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০১/১০/২০২৪', amount: 1000, voucherNo: 'TR-KB-872', method: 'ব্যাংক অ্যাকাউন্ট ট্রান্সফার', notes: 'প্রাথমিক অগ্রিম জমা' },
      { date: '১৪/১০/২০২৪', amount: 515, voucherNo: 'CR-KB-9740', method: 'নগদ ক্যাশ কাউন্টার পরিশোধ', notes: 'সমন্বয় জমা' },
    ],
  },
  {
    id: 'BILL-06',
    gpfNo: 'GPF-৪২০৩৫',
    name: 'মো: জহিরুল ইসলাম',
    designation: 'অফিসার (ক্যাশ)',
    department: 'শাখা নিয়ন্ত্রণ বিভাগ',
    mobile: '01730-789012',
    officerMeals: 21,
    guestMeals: 0,
    totalMeals: 21,
    mealCost: 1365,
    messFee: 150,
    totalBill: 1515,
    advancePaid: 2000,
    netDue: -485,
    status: 'refund',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '০২/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '১৬/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছ', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '২৩/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২৯/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
      { date: '৩০/১০/২০২৪', dayName: 'বুধবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'ডিম ভুনা', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০১/১০/২০২৪', amount: 2000, voucherNo: 'TR-KB-865', method: 'ক্যাশ কাউন্টারে জমা', notes: 'অগ্রিম মেস চার্জ জমা' },
    ],
  },
  {
    id: 'BILL-07',
    gpfNo: 'GPF-৫৮৯১০',
    name: 'রেহানা পারভীন',
    designation: 'সিনিয়র প্রিন্সিপাল অফিসার',
    department: 'কর্মী ব্যবস্থাপনা বিভাগ',
    mobile: '01815-890123',
    officerMeals: 17,
    guestMeals: 1,
    totalMeals: 18,
    mealCost: 1170,
    messFee: 150,
    totalBill: 1320,
    advancePaid: 1200,
    netDue: 120,
    status: 'due',
    mealBookingDates: [
      { date: '০১/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '০৩/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '০৬/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের কালিয়া', status: 'consumed' },
      { date: '০৭/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '০৮/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছের ঝোল', status: 'consumed' },
      { date: '১০/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '১৩/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '১৪/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '১৫/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 1, totalMeals: 2, menuItem: 'মাছের কালিয়া ও অতিথি লাঞ্চ', status: 'consumed' },
      { date: '১৭/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'কাতল মাছ', status: 'consumed' },
      { date: '২০/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির ঝোল', status: 'consumed' },
      { date: '২১/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২২/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'চিকেন কারি', status: 'consumed' },
      { date: '২৪/১০/২০২৪', dayName: 'বৃহস্পতিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের ঝোল', status: 'consumed' },
      { date: '২৭/১০/২০২৪', dayName: 'রবিবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মুরগির মাংস', status: 'consumed' },
      { date: '২৮/১০/২০২৪', dayName: 'সোমবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'রুই মাছ', status: 'consumed' },
      { date: '২৯/১০/২০২৪', dayName: 'মঙ্গলবার', officerMeals: 1, guestMeals: 0, totalMeals: 1, menuItem: 'মাছের কালিয়া', status: 'consumed' },
    ],
    advanceDeposits: [
      { date: '০৩/১০/২০২৪', amount: 1200, voucherNo: 'TR-KB-830', method: 'ব্যাংক একাউন্ট ডেবিট', notes: 'মাসিক অগ্রিম জমা' },
    ],
  },
];

export const INITIAL_WEEKLY_MENU: import('./types').WeeklyMenuDay[] = [
  {
    id: 'SUN',
    dayNameBn: 'রবিবার',
    dayNameEn: 'Sunday',
    isHoliday: false,
    mainDish: 'রুই মাছের কালিয়া',
    mainDishEn: 'Rui Fish Kalia Curry',
    sideDish1: 'পাঁচমিশেলি মৌসুমি সবজি ভাজি',
    sideDish1En: 'Seasonal Mixed Vegetable Stir-fry',
    sideDish2: 'ঘন মুগ ডাল ফোঁড়ন',
    sideDish2En: 'Thick Moong Dal with Cumin Tempering',
    riceDish: 'গরম মিনিকেট সাদা ভাত',
    riceDishEn: 'Hot Steamed Miniket Rice',
    specialItem: 'লেবু ও কাঁচামরিচ',
    specialItemEn: 'Lemon & Green Chilies',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLZzYzg259kTYLHtjwgcRZ36rsxzRruGqHBpbXedflJULbcePHVZL2H9lCdQtihFG4h_21wX5sJ6thK_Kp-tcPGjblCKF4aKkz3MAewxvUNVNWov3-Oya4zfxCyVOgO1DpPjCGxBPp3rUvyOrzZFZy9llxjDzdGLxmQysSkpLS05q2b76VWMI2JMeEoT2lESndmjGeaQL7z1MnI-H7qt2MQxFWcGzFKcV081MwrtxH-5Rs89BcPxQ-',
  },
  {
    id: 'MON',
    dayNameBn: 'সোমবার',
    dayNameEn: 'Monday',
    isHoliday: false,
    mainDish: 'দেশি মুরগির আলু দিয়ে ঝোল',
    mainDishEn: 'Desi Chicken Curry with Potatoes',
    sideDish1: 'পটোল ও আলু ভাজা',
    sideDish1En: 'Pointed Gourd & Potato Fry',
    sideDish2: 'মসুর ডাল রসুন বাগার',
    sideDish2En: 'Red Lentil Dal with Garlic Tempering',
    riceDish: 'গরম সাদা ভাত',
    riceDishEn: 'Hot Steamed Rice',
    specialItem: 'সালাদ ও লেবু',
    specialItemEn: 'Fresh Salad & Lemon Slice',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdiUOK8h_DDjWmom6BtQwCyYebN3FBoRqefPY1fZvg9Tre5MUnJxBHfax1_VMTQ8AKS16ba8aKN_cHrp-I5tDo9r_F0ekgGdTG5Ib88o0iX6ZwAPxCszXYkmj50wymlDFPssBDspJhmhs6G6zq3nFCmIn7UuR7lU-6mxinAFr3XlEpUBqtzt9iRcFhTD1j1TCG3sYjegT6AK5ny-pavYLBbabFS0xY_z9-0bc1M9d3RzUht4BQZEh-',
  },
  {
    id: 'TUE',
    dayNameBn: 'মঙ্গলবার (আজকের মেনু)',
    dayNameEn: 'Tuesday (Today)',
    isHoliday: false,
    mainDish: 'তাজা রুই মাছের ঝোল',
    mainDishEn: 'Fresh Rui Fish Curry Broth',
    sideDish1: 'মৌসুমি ফুলকপি-আলুর তরকারি',
    sideDish1En: 'Seasonal Cauliflower & Potato Curry',
    sideDish2: 'ঘন মসুর ডাল',
    sideDish2En: 'Thick Red Lentil Dal',
    riceDish: 'সুগন্ধি সাদা ভাত',
    riceDishEn: 'Fragrant Steamed Rice',
    specialItem: 'শসা ও টমেটোর সালাদ',
    specialItemEn: 'Cucumber & Tomato Salad',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLZzYzg259kTYLHtjwgcRZ36rsxzRruGqHBpbXedflJULbcePHVZL2H9lCdQtihFG4h_21wX5sJ6thK_Kp-tcPGjblCKF4aKkz3MAewxvUNVNWov3-Oya4zfxCyVOgO1DpPjCGxBPp3rUvyOrzZFZy9llxjDzdGLxmQysSkpLS05q2b76VWMI2JMeEoT2lESndmjGeaQL7z1MnI-H7qt2MQxFWcGzFKcV081MwrtxH-5Rs89BcPxQ-',
  },
  {
    id: 'WED',
    dayNameBn: 'বুধবার',
    dayNameEn: 'Wednesday',
    isHoliday: false,
    mainDish: 'ডিম ভুনা (দেশি স্টাইল ২ পিস)',
    mainDishEn: 'Egg Bhuna Curry (Desi Style 2 pcs)',
    sideDish1: 'বেগুন ভর্তা ও আলু ভর্তা',
    sideDish1En: 'Mashed Eggplant & Mashed Potato (Bhorta)',
    sideDish2: 'টক ডাল / চাটনি',
    sideDish2En: 'Tangy Dal / Fresh Chutney',
    riceDish: 'ভুনা খিচুড়ি অথবা গরম সাদা ভাত',
    riceDishEn: 'Bhuna Khichuri or Steamed Rice',
    specialItem: 'দেশি ঘি ও কাঁচা মরিচ',
    specialItemEn: 'Desi Pure Ghee & Green Chilies',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrLevV5sTh15e2pASCD_kCpMgLddywNH6xLGK5n8iMy7OG7IrxBIev_8z3hYnnBcJwtOQdI03AIUkni8Y0jsShnPgb7Ytu2LD2dzmxQAYVqG3V-VzSklZk7SjQCFxcahc4u_Um5fjCzBShTf5GwjwgFYa_SLaPdI9WTdVydmEYDCh6aKnTmT8TslGfw2tDDdl3w3diqMRcGz2MYeRbdpWqJ0usyKpOAizdL45g8bamWczFOQb48MZY',
  },
  {
    id: 'THU',
    dayNameBn: 'বৃহস্পতিবার (স্পেশাল লাঞ্চ)',
    dayNameEn: 'Thursday (Special Feast)',
    isHoliday: false,
    mainDish: 'খাসির মাংসের রেজালা / বিফ ভুনা',
    mainDishEn: 'Mutton Rezala / Beef Bhuna',
    sideDish1: 'জালি কাবাব ও রায়তা',
    sideDish1En: 'Jali Kabab & Mint Raita',
    sideDish2: 'ঘন ডাল ও কাশ্মীরি সালাদ',
    sideDish2En: 'Thick Dal & Kashmiri Salad',
    riceDish: 'স্পেশাল সুগন্ধি মোরগ পোলাও / সাদা ভাত',
    riceDishEn: 'Special Morog Polao / Steamed Rice',
    specialItem: 'মিষ্টি দই ও কোমল পানীয়',
    specialItemEn: 'Sweet Yogurt & Soft Drink',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNaQtG85SgSfGYGLn1DqY0YL6bajlYXHGVuVgU_uHf53tgJ-sYvw-f2h4i2hLBXOdTJuMzhJsfshS01yY6pffHOMIOX0tbb117XfUHV5-h6AeV0JQdd2k-JRyPIrn39vSp_prXNuc7lGDtWX-m8nF5Cq11lNGS2KYx4Gxmgjuw-6PbaJ4tZecp4jLOywqL7TqAV9GY8ILkneliodDF3ObI4_GNsvqT34kZ8gsI1BZuP1g3OsSTZO8k',
  },
  {
    id: 'FRI',
    dayNameBn: 'শুক্রবার',
    dayNameEn: 'Friday',
    isHoliday: true,
    mainDish: 'ক্যান্টিন সাপ্তাহিক ছুটি বন্ধ',
    mainDishEn: 'Canteen Closed (Weekend Holiday)',
    sideDish1: '-',
    sideDish1En: '-',
    sideDish2: '-',
    sideDish2En: '-',
    riceDish: '-',
    riceDishEn: '-',
    specialItem: 'বন্ধ',
    specialItemEn: 'Closed',
    imageUrl: '',
  },
  {
    id: 'SAT',
    dayNameBn: 'শনিবার',
    dayNameEn: 'Saturday',
    isHoliday: true,
    mainDish: 'ক্যান্টিন সাপ্তাহিক ছুটি বন্ধ',
    mainDishEn: 'Canteen Closed (Weekend Holiday)',
    sideDish1: '-',
    sideDish1En: '-',
    sideDish2: '-',
    sideDish2En: '-',
    riceDish: '-',
    riceDishEn: '-',
    specialItem: 'বন্ধ',
    specialItemEn: 'Closed',
    imageUrl: '',
  },
];

export const INITIAL_NOTICES: import('./types').CanteenNotice[] = [
  {
    id: 'N-01',
    title: 'পবিত্র ঈদ-উল-ফিতরের ছুটিকালীন মিল বন্ধ থাকবে',
    content: 'সরকারি সাধারণ ছুটি শুরু হওয়ার আগের দিন দুপুর পর্যন্ত ক্যান্টিন স্বাভাবিকভাবে চালু থাকবে। ছুটিকালীন কোনো মিল কাউন্ট হবে না এবং কোনো ফি প্রযোজ্য হবে না।',
    type: 'holiday',
    date: '১২ অক্টোবর ২০২৪',
    author: 'মেস প্রশাসন ও ক্যান্টিন কমিটি',
  },
  {
    id: 'N-02',
    title: 'মিল অফ/অন করার কাট-অফ সময়: পূর্ববর্তী দিন বিকাল ৫:০০টা',
    content: 'বাজারের প্রস্তুতি, মসলা ক্রয় ও রান্নার অপচয় সম্পূর্ণ রোধে বিকাল ৫:০০ ঘটিকার পরে কোনো মিল অন/অফ অনুরোধ স্বয়ংক্রিয়ভাবে গ্রহণ করা হবে না। জরুরি অফিসিয়াল প্রয়োজনে মেস ম্যানেজারের সাথে সরাসরি যোগাযোগ করুন।',
    type: 'urgent',
    date: '০১ অক্টোবর ২০২৪',
    author: 'মেস ইনচার্জ (মহাব্যবস্থাপক)',
  },
  {
    id: 'N-03',
    title: 'আগামী বৃহস্পতিবার বিশেষ লাঞ্চ আয়োজন সংক্রান্ত',
    content: 'বোর্ড অব ডিরেক্টরস মিটিং উপলক্ষে আগামী বৃহস্পতিবার স্পেশাল রেজালা ও পোলাও প্রস্তুত করা হবে। কোনো অতিথি মিল প্রয়োজন হলে বুধবার ৪টার মধ্যে সংখ্যা নিশ্চিত করুন।',
    type: 'general',
    date: '১৪ অক্টোবর ২০২৪',
    author: 'সহকারী মেস ম্যানেজার (হিসাব বিভাগ)',
  },
];

export const INITIAL_ALL_MEMBERS: UserProfile[] = [
  INITIAL_PROFILES.member,
  INITIAL_PROFILES.admin,
  INITIAL_PROFILES.coadmin,
  {
    id: 'GPF-১৬৭৮২',
    name: 'মোছা: নাসরিন সুলতানা',
    nameEn: 'Mst. Nasrin Sultana',
    role: 'member',
    designation: 'প্রিন্সিপাল অফিসার',
    designationEn: 'Principal Officer',
    department: 'ঋণ ও অগ্রিম বিভাগ',
    departmentEn: 'Loan and Advance Department',
    gpfNo: 'GPF-১৬৭৮২',
    mobile: '০১৭১২-৮৮৭৭৬৬',
    email: 'nasrin.loan@kbl.gov.bd',
    roomNo: '৫০২, প্রধান কার্যালয়',
    roomNoEn: 'Room 502, Head Office',
    monthlyMeals: 22,
    upcomingMeals: 1,
    advanceBalance: 1500,
    dueAmount: 80,
    todayMealStatus: 'on',
    mealRate: 65,
  },
  {
    id: 'GPF-২৯০১১',
    name: 'কাজী মিজানুর রহমান',
    nameEn: 'Kazi Mizanur Rahman',
    role: 'member',
    designation: 'সহকারী মহাব্যবস্থাপক',
    designationEn: 'Assistant General Manager',
    department: 'নিরীক্ষা ও পরিদর্শন বিভাগ',
    departmentEn: 'Audit and Inspection Department',
    gpfNo: 'GPF-২৯০১১',
    mobile: '০১৯১১-২২৩৩৪৪',
    email: 'mizan.audit@kbl.gov.bd',
    roomNo: '২০৫, অডিট ভবন',
    roomNoEn: 'Room 205, Audit Building',
    monthlyMeals: 21,
    upcomingMeals: 0,
    todayMealStatus: 'off',
    advanceBalance: 1515,
    dueAmount: 0,
    mealRate: 65,
  },
  {
    id: 'GPF-৪২০৩৫',
    name: 'মো: জহিরুল ইসলাম',
    nameEn: 'Md. Zahirul Islam',
    role: 'member',
    designation: 'অফিসার (ক্যাশ)',
    designationEn: 'Officer (Cash)',
    department: 'শাখা নিয়ন্ত্রণ বিভাগ',
    departmentEn: 'Branch Control Department',
    gpfNo: 'GPF-৪২০৩৫',
    mobile: '০১৮১৬-৭৭৮৮৯৯',
    email: 'zahir.cash@kbl.gov.bd',
    roomNo: '১০৩, নিচতলা',
    roomNoEn: 'Room 103, Ground Floor',
    monthlyMeals: 21,
    upcomingMeals: 1,
    todayMealStatus: 'on',
    advanceBalance: 2000,
    dueAmount: 0,
    mealRate: 65,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  // 1. Common Services Department
  {
    id: 'dept-seba',
    name: 'সাধারণ সেবা বিভাগ',
    nameEn: 'Common Services Department',
    code: 'SEBA',
    adminGpf: 'GPF-৫১২৩৪',
    adminName: 'মো: সাইফুল ইসলাম',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 2. Loan and Advance Department
  {
    id: 'dept-lad',
    name: 'ঋণ ও অগ্রিম বিভাগ',
    nameEn: 'Loan and Advance Department',
    code: 'LAD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: 'GPF-৬৭৮৯০',
    coAdminName: 'নাসরিন আক্তার',
  },
  // 3. Managing Director’s Squad
  {
    id: 'dept-mds',
    name: 'ব্যবস্থাপনা পরিচালকের স্কোয়াড',
    nameEn: 'Managing Director’s Squad',
    code: 'MDS',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 4. Loan Recovery and Monitoring Department
  {
    id: 'dept-lrd',
    name: 'ঋণ আদায় ও পর্যবেক্ষণ বিভাগ',
    nameEn: 'Loan Recovery and Monitoring Department',
    code: 'LRD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 5. Personnel Management Department
  {
    id: 'dept-pmthrd',
    name: 'কর্মী ব্যবস্থাপনা বিভাগ',
    nameEn: 'Personnel Management Department',
    code: 'PMTHRD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 6. Law, Research and Development Department
  {
    id: 'dept-lred',
    name: 'আইন, গবেষণা ও উন্নয়ন বিভাগ',
    nameEn: 'Law, Research and Development Department',
    code: 'LRED',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 7. Central Accounts and Fund Management Department
  {
    id: 'dept-cafmd',
    name: 'কেন্দ্রীয় হিসাব ও তহবিল ব্যবস্থাপনা বিভাগ',
    nameEn: 'Central Accounts and Fund Management Department',
    code: 'CAFMD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: 'GPF-৩৮৯২০',
    coAdminName: 'মোহাম্মদ রহিম উল্লাহ',
  },
  // 8. IT Operation
  {
    id: 'dept-it-op',
    name: 'আইটি অপারেশন',
    nameEn: 'IT Operation',
    code: 'IT_OP',
    adminGpf: '',
    adminName: '',
    coAdminGpf: 'GPF-২৪৯০',
    coAdminName: 'হাসান মাহমুদ',
  },
  // 9. Real Asset and Engineering Department
  {
    id: 'dept-engg',
    name: 'বাস্তব সম্পদ ও প্রকৌশল বিভাগ',
    nameEn: 'Real Asset and Engineering Department',
    code: 'ENGG',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 10. Discipline and Appeal Department
  {
    id: 'dept-daip',
    name: 'শৃঙ্খলা ও আপীল বিভাগ',
    nameEn: 'Discipline and Appeal Department',
    code: 'DAIP',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 11. Audit and Inspection Department
  {
    id: 'dept-aid',
    name: 'নিরীক্ষা ও পরিদর্শন বিভাগ',
    nameEn: 'Audit and Inspection Department',
    code: 'AID',
    adminGpf: 'GPF-২৯০১১',
    adminName: 'কাজী মিজানুর রহমান',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 12. IT Systems, Research and Development Department
  {
    id: 'dept-it-sys',
    name: 'আইটি সিস্টেম, রিসার্চ এন্ড ডেভেলপমেন্ট বিভাগ',
    nameEn: 'IT Systems, Research and Development Department',
    code: 'IT_SYS',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 13. Branch Control Department
  {
    id: 'dept-bcd',
    name: 'শাখা নিয়ন্ত্রণ বিভাগ',
    nameEn: 'Branch Control Department',
    code: 'BCD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: 'GPF-৪২০৩৫',
    coAdminName: 'মো: জহিরুল ইসলাম',
  },
  // 14. Budget, Expenditure Control and Accounts Reconciliation Department
  {
    id: 'dept-becard',
    name: 'বাজেট, ব্যয় নিয়ন্ত্রণ ও হিসাব সমন্বয় বিভাগ',
    nameEn: 'Budget, Expenditure Control and Accounts Reconciliation Department',
    code: 'BECARD',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
  // 15. Employee Welfare, Training and Human Resources Department
  {
    id: 'dept-emp-wel',
    name: 'কর্মী কল্যাণ, প্রশিক্ষণ ও মানব সম্পদ বিভাগ',
    nameEn: 'Employee Welfare, Training and Human Resources Department',
    code: 'EMP_WEL',
    adminGpf: '',
    adminName: '',
    coAdminGpf: '',
    coAdminName: '',
  },
];

export const getInitialMealCall = (targetDate: Date = new Date()): MealCallState => {
  const day = targetDate.getDate();
  const month = targetDate.getMonth();
  const year = targetDate.getFullYear();
  const daysInMonth = new Date(year, month + 1, 0).getDate();

  const toBnDigits = (n: number | string) =>
    String(n).replace(/[0-9]/g, (d) => '০১২৩৪৫৬৭৮৯'[parseInt(d, 10)]);

  const monthNamesBn = [
    'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
    'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
  ];
  const monthNamesEn = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];

  const nextDay = Math.min(day + 1, daysInMonth);
  const thirdDay = Math.min(day + 2, daysInMonth);

  return {
    isActive: true,
    targetDate: `${toBnDigits(day)} ${monthNamesBn[month]} ${toBnDigits(year)}`,
    targetDateEn: `${day} ${monthNamesEn[month]} ${year}`,
    cutoffTime: 'বিকাল ৫:০০ টা',
    cutoffTimeEn: '5:00 PM',
    calledBy: 'মো: সাইফুল ইসলাম',
    calledByEn: 'Md. Saiful Islam',
    calledByGpf: 'GPF-৫১২৩৪',
    calledByRole: 'admin',
    calledAt: 'সকাল ০৯:১৫ টা',
    calledAtEn: '09:15 AM',
    menuHighlight: 'আজকের স্পেশাল মেন্যু: রুই মাছের দোপেঁয়াজা, ডাল ও সালাদ',
    menuHighlightEn: "Today's Special Menu: Rui Fish Dopiaza, Dal & Salad",
    customNote: 'সকল সদস্যকে বিকাল ৫:০০ ঘটিকার মধ্যে মিল নিশ্চিত বা পরিবর্তনের অনুরোধ করা হচ্ছে।',
    customNoteEn: 'All members are requested to confirm or modify meals before 5:00 PM.',
    calledDates: [day, nextDay, thirdDay],
  };
};

export const INITIAL_MEAL_CALL: MealCallState = getInitialMealCall();

